spring:
  messages:
    basename: validation
  datasource:
    url: jdbc:postgresql://localhost:5432/available_books?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
  application:
    name: BOOKS-AVAILABLE-SERVICE
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
feign:
  client:
    config:
      forecasts:
        name: BOOKS-FORECAST-SERVICE
        path: /api/v1/forecast
eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/
server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      forecastBreaker: &circuitbreakerConfig
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      forecastRetry: &retryConfig
        maxAttempts: 3
        waitDuration: 30s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2