spring:
  messages:
    basename: validation
  datasource:
    url: jdbc:postgresql://localhost:5432/available_books?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  application:
    name: BOOKS-AVAILABLE-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://eureka@localhost:8761/eureka/
server:
  port: 8081