spring:
  ai:
    ollama:
      base-url: http://ollama:11434/
      model: deepseek-r1:7b
  datasource:
    url: ${PGSQL_JDBC_URL:jdbc:postgresql://postgredb:5432/forecast_books?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
    username: ${PGSQL_USERNAME:def_user}
    password: ${PGSQL_PASSWORD:pass}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/